services:
  app:
    build: .
    container_name: vending_app
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - vending-network

  mongo:
    image: mongo:6
    container_name: vending_mongo
    restart: always
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: StrongPassword123
      MONGO_INITDB_DATABASE: vending-machines
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - vending-network

  redis:
    image: redis:7-alpine
    container_name: vending_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - vending-network

  caddy:
    image: caddy:2.8
    container_name: vending_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - vending-network

volumes:
  mongo_data:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  vending-network:
    driver: bridge


