import {  Types, Document } from 'mongoose';

export enum machineType {
  SLOT = 'slot', 
  COFFEE = 'coffee',
  COMBO = 'combo',
}

export enum MachineStatus {
  ACTIVE = 'active',
  MAINTENANCE = 'maintenance',
  OUT_OF_SERVICE = 'out_of_service'
}

export enum UnitOfMeasure {
  ML = 'ml',
  GRAMS = 'grams',
  PUMPS = 'pumps',
  ITEMS = 'items'
}

export enum AuditAction {
  MACHINE_CREATED = 'MACHINE_CREATED',
  MACHINE_UPDATED = 'MACHINE_UPDATED',
  SKU_CREATED = 'SKU_CREATED',
  SKU_UPDATED = 'SKU_UPDATED',
  SKU_DELETED = 'SKU_DELETED',
  SKU_SOLD = 'SKU_SOLD',
  SKU_RESTOCKED = 'SKU_RESTOCKED',
  INGREDIENT_CREATED = 'INGREDIENT_CREATED',
  INGREDIENT_UPDATED = 'INGREDIENT_UPDATED',
  INGREDIENT_DELETED = 'INGREDIENT_DELETED',
  INGREDIENT_CONSUMED = 'INGREDIENT_CONSUMED',
  INGREDIENT_REFILLED = 'INGREDIENT_REFILLED',
  CANISTER_CREATED = 'CANISTER_CREATED',
  CANISTER_UPDATED = 'CANISTER_UPDATED',
  CANISTER_DELETED = 'CANISTER_DELETED',
  CANISTER_REFILLED = 'CANISTER_REFILLED',
  SLOT_CREATED = 'SLOT_CREATED',
  SLOT_UPDATED = 'SLOT_UPDATED',
  SLOT_DELETED = 'SLOT_DELETED',
  TRAY_CREATED = 'TRAY_CREATED',
  TRAY_UPDATED = 'TRAY_UPDATED',
  TRAY_DELETED = 'TRAY_DELETED',
  RECIPE_CREATED = 'RECIPE_CREATED',
  RECIPE_UPDATED = 'RECIPE_UPDATED',
  RECIPE_DELETED = 'RECIPE_DELETED',
  RECIPE_OUT_OF_STOCK = 'RECIPE_OUT_OF_STOCK'
}

export interface RecipeIngredient extends Document {
  ingredientId: Types.ObjectId;
  quantity: number;
  unit: UnitOfMeasure;
  _id: Types.ObjectId;
}
